name: TastyHub Backend CI   // CI pipeline for TastyHub backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest   // runs on the latest Ubuntu environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci || npm install
        run: echo " It's Pishou, i am saying , Dependencies installed !! "

      - name: Run tests
        run: npm test
